require("config.options")
require("config.keymaps")
require("config.lsp")

require("plugins.fyler")
require("plugins.fzf")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.blink")
require("plugins.notify")
require("plugins.alpha")
require("plugins.matugen")

require("mini.icons").setup({})
