require("config.options")
require("config.keymaps")
require("config.lsp")

require("plugins.fyler")
require("plugins.which-key")
require("plugins.fzf")
require("plugins.lualine")
require("plugins.noice")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.blink")
require("plugins.notify")
require("plugins.trouble")
require("plugins.alpha")
require("plugins.matugen")
